# Generated by Django 4.1 on 2022-08-27 02:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2022, 8, 27, 2, 23, 12, 257534),
            ),
            preserve_default=False,
        ),
    ]
