# Generated by Django 4.1 on 2022-08-27 02:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_company_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
